IT-3317: Create a containerized reverse proxy for use in a modular SC notebook product
Sage-Bionetworks/notebook-reverse-proxy pull request #1
Opened 2023-12-11 18:42 UTC by brucehoff

This repo' creates an Apache2 reverse proxy as a Docker container.
Two 'flavors' of the container are created, one suitable for R-Studio and one for Juptyer.
The README provides the Docker `run` commands to start up the containers to run notebooks on a Service Catalog EC2 instance.

2023-12-12 19:48 UTC, xschildw approved these changes
Makes sense to me.

2023-12-12 20:25 UTC, brucehoff commented on tests/unit/test_access.py
Thanks, I noticed the original RStudio Notebook product lacked any tests of the Python code and wanted to add them.

2023-12-12 20:27 UTC, zaro0508 requested changes
wondering why you created this in `Sage-Bionetworks` org and not in `Sage-Bionetworks-IT` org?

2023-12-12 20:27 UTC, zaro0508 commented on .github/workflows/main.yml
> +  docker-deploy-jupyter:
this will deploy on a PR.  i think makes sense to  deploy to ghcr on a merge?  you'll need an `if` condition if you only want to deploy on merge.

2023-12-12 20:27 UTC, zaro0508 commented on .github/workflows/main.yml
> +  docker-deploy-rstudio:
same here

2023-12-12 20:27 UTC, zaro0508 commented on .pre-commit-config.yaml
> +  - repo: https://github.com/awslabs/cfn-python-lint
do you need this?

2023-12-12 20:27 UTC, zaro0508 commented on Dockerfile
> +# patterned after https://github.com/Sage-Bionetworks-IT/packer-rstudio/blob/master/src/playbook.yaml#L76-L91
this is the most important thing from that playbook.. 
```
    # The mod_python provided by apt in Ubuntu 22.04 intermittently fails with segmentation faults.
    # mod_python is only supported from master branch at https://github.com/grisha/mod_python.git
```

i would include it in this file

2023-12-12 20:27 UTC, zaro0508 commented on README.md
> +Docker container with Apache reverse proxy for Service Catalog notebook product
to provide more context, would it be possible to provide general info on why this repo exists and how it's used by the service catalog?

2023-12-12 20:27 UTC, zaro0508 commented on jupyter_proxy.conf
> +<VirtualHost _default_:443>
how does this file get installed into the docker container?

2023-12-12 20:27 UTC, zaro0508 commented on rstudio_proxy.conf
> +<VirtualHost _default_:443>
how does this file get installed into the docker container?

2023-12-13 03:59 UTC, brucehoff commented on jupyter_proxy.conf
> +<VirtualHost _default_:443>
https://github.com/Sage-Bionetworks/notebook-reverse-proxy/pull/1/files#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R32

2023-12-13 04:00 UTC, brucehoff commented on rstudio_proxy.conf
> +<VirtualHost _default_:443>
Same as above:

https://github.com/Sage-Bionetworks/notebook-reverse-proxy/pull/1/files#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R32

2023-12-13 19:25 UTC, zaro0508 requested changes
@brucehoff you didn't answer my question about Sage-Bionetworks-IT repo from the previous review?

2023-12-13 19:25 UTC, zaro0508 commented on README.md
> +docker run -d -p 443:443 --name reverse-proxy \
does this need `sudo` like the one below?

2023-12-13 19:25 UTC, zaro0508 commented on README.md
> +mkdir /home/ssm-user/workdir
I believe using the `ssm-user` assumes that the SSM agent is installed on the instance.  That means this will only work if a AWS linux instance is used or that the SSM agent has been installed on the non-aws linux instances.  Maybe we should make that clear in the docs?

2023-12-13 19:25 UTC, zaro0508 commented on README.md
> +docker run -d -p 443:443 --name reverse-proxy \
sudo?

2023-12-13 19:25 UTC, zaro0508 commented on README.md
> +--network ${NETWORK_NAME} quay.io/jupyter/base-notebook \
instead of hard coding the image it would be better if we parameterize it to make it easier to update going forward.

Also would I think it proably makes sense to pin this to a specific tag or version instead of just using the latest.

2023-12-13 19:25 UTC, zaro0508 commented on README.md
> +rocker/rstudio
pin?

2023-12-13 20:37 UTC, brucehoff commented
> @brucehoff you didn't answer my question about Sage-Bionetworks-IT repo from the previous review?

Our infrastructure repo's are spread across two organizations, Sage-Bionetworks and Sage-Bionetworks-IT.

2023-12-14 02:00 UTC, brucehoff commented on .github/workflows/docker_build.yml
> +        if: github.event_name != 'pull_request'
> do we need this? isn't it already taken care of by the conditional in main.yml?

I had it right the first time.  Leaving it here, as opposed to in main.yml (but bumping it up from the 'step level' to the 'job' level ) means we have just a single `if`.

2023-12-14 02:01 UTC, brucehoff commented on .github/workflows/main.yml
> +    if: ${{github.ref == 'refs/heads/main'}}
> i assume we want to be able to tag, deploy and eventually use a tagged version instead of a version from the main branch? this won't deploy when a tag is created.

Yes, see my comment above.

2023-12-14 02:04 UTC, brucehoff commented on README.md
> +docker run -d -p 443:443 --name reverse-proxy \
It depends on the permissions of the user running `docker run`.  This is just general guidance.  The assumption is that the reader knows how to use Docker and whether they have to use `sudo`.

2023-12-14 02:06 UTC, brucehoff commented on README.md
> +mkdir /home/ssm-user/workdir
Done: I'm clarifying that `/home/ssm-user` is just an example home directory.

2023-12-14 02:07 UTC, brucehoff commented on README.md
> +docker run -d -p 443:443 --name reverse-proxy \
Please see above.

2023-12-14 02:16 UTC, brucehoff commented on README.md
> +--network ${NETWORK_NAME} quay.io/jupyter/base-notebook \
I can add the appropriate guidance in this README, but how the image is encoded is the subject of the Service Catalog product.

2023-12-14 16:42 UTC, zaro0508 requested changes

2023-12-14 16:42 UTC, zaro0508 commented on .github/workflows/docker_build.yml
> +    if: github.event_name != 'pull_request'
This will build on a push from any branch or a merge to any branch.  I don't think we want to push the container when some random branch is push to github?

2023-12-14 16:42 UTC, zaro0508 commented on .github/workflows/main.yml
> +  tests:
the test job should include building the docker container but NOT pushing it to the registery.

2023-12-14 16:42 UTC, zaro0508 commented on .github/workflows/docker_build.yml
> +      - name: Build and push Docker image
I think you should split this into two jobs `build` and `build-and-publish`.  We want to build the container on a PR but not publish it to the registry.  We want to build and publish on a merge to master branch or a tag

2023-12-14 16:42 UTC, zaro0508 commented on README.md
> +docker run -d -p 443:443 --name reverse-proxy \
it was just odd that the example to run the notebook (below) uses `sudo` while this one doesn't

2023-12-14 16:48 UTC, zaro0508 commented
> Our infrastructure repo's are spread across two organizations, Sage-Bionetworks and Sage-Bionetworks-IT.

I kinda already knew that however it doesn't answer my inquiry as to why you decided on one over the other.  I mean we created the Sage-Bionetworks-IT org for a reason.  If this repo is specifically for IT should it not be in the IT repo?

2023-12-15 18:58 UTC, brucehoff commented on .github/workflows/docker_build.yml
> +      - name: Build and push Docker image
@zaro0508 
> We want to build the container on a PR but not publish it to the registry.

This workflow already does that:
>  push: ${{ github.event_name != 'pull_request' }}

will be false for a pull request and so it won't push to GHCR.

2023-12-15 20:25 UTC, brucehoff commented on .github/workflows/docker_build.yml
> +    if: github.event_name != 'pull_request'
> This will build on a push from any branch or a merge to any branch. I don't think we want to push the container when some random branch is push to github?

See the update, which will build on all branches and on PRz, but only publish the container on a push/merge to 'main'.

2023-12-15 20:25 UTC, brucehoff commented on .github/workflows/main.yml
> +  tests:
> the test job should include building the docker container but NOT pushing it to the registery.

See the update, which will build on all branches and on PRs, but only publish the container on a push/merge to 'main'.

2023-12-15 20:26 UTC, brucehoff commented
> > Our infrastructure repo's are spread across two organizations, Sage-Bionetworks and Sage-Bionetworks-IT.
> 
> I kinda already knew that however it doesn't answer my inquiry as to why you decided on one over the other. I mean we created the Sage-Bionetworks-IT org for a reason. If this repo is specifically for IT should it not be in the IT org?

We can move to Sage-Bionetworks-IT.

2023-12-15 20:44 UTC, brucehoff commented
Closing this PR in favor of https://github.com/Sage-Bionetworks-IT/notebook-reverse-proxy/pull/1

2023-12-15 20:44 UTC, closed without merging